version: "3.8"
services:
  nextjs-dev:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./pages:/app/pages
      - ./app:/app/app # if using app directory
      - ./components:/app/components
      - ./styles:/app/styles
      - ./public:/app/public
      - ./prisma:/app/prisma
      - /app/node_modules # Prevent overwriting node_modules
      - /app/.next # Prevent overwriting .next cache
    environment:
      - NODE_ENV=development
