# .github/workflows/create-mdx-file.yml
name: Create MDX File

on:
  repository_dispatch:
    types: [create-mdx-file]

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create MDX file
        run: |
          # Create content directory if it doesn't exist
          mkdir -p public/content

          # Create the MDX file
          cat > "public/content/${{ github.event.client_payload.slug }}.mdx" << 'EOF'
          ${{ github.event.client_payload.content }}
          EOF

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "public/content/${{ github.event.client_payload.slug }}.mdx"
          git commit -m "Add new blog post: ${{ github.event.client_payload.title }}"
          git push

      - name: Trigger deployment (optional)
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: deploy-site
